image:
  repository: ghcr.io/k8s-at-home/qbittorrent
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  config:
    enabled: true
    emptyDir: 
      enabled: true
    mountPath: /config

addons:
  promtail:
    enabled: true
    loki:
    - http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    logs:
    - name: qbittorrent
      path: /config/data/qBittorrent/logs/*.log
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
